include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.g.dart'
    - '**/generated_plugin_registrant.dart'

linter:
  rules:
    prefer_single_quotes: true
    prefer_ralative_imports: true
    require_trailing_commas: true
    always_declare_return_types: true
    library_private_types_in_public_api: false
    use_key_in_widget_constructors: false